/*
*
1)  SIGNED AND UNSIGNED
    FOR NOW I AM WRITING ALL THE UNSIGNED INSTRUCTIONS EXACTLY AS THEIR SIGNED COUNTERPARTS.
    THE STALLS AND STUFF WOULD REMAIN CONSISTENT BUT SOME TYPECASTING MAY BE NEEDED LATER TO
    GET THE CORRECT NUMERIC RESULT


*/